:type: plugin
:status: published
:title: Audit Classified Access Plugin
:link: _audit_classified_access_plugin
:plugintypes: postquery
:summary: Audits classified access based off specific metacard attributes and configured values.

Audits when a classified metacard is being accessed.
The determination for classification is based on configurable values for the attributes Classification, Releasability, DisseminationControls, and Codewords.

===== Installing Audit Classified Access Plugin

The Audit Classified Access Plugin is not installed by default in a standard installation in the ${alliance-security} application.

To install:

. Navigate to the *${admin-console}*.
. Select the *System* tab.
. Select the *Features* tab.
. Install the `security-auditclassifiedaccess` feature.

===== Configuring Audit Classified Access Plugin

To configure the Audit Classified Access Plugin:

. Navigate to the *${admin-console}*.
. Select the *${alliance-security}* application.
. Select *Configuration* tab.
. Select *Audit Classified Access Plugin*.

See <<{reference-prefix}org.codice.alliance.catalog.plugin.auditclassified.AuditClassifiedAccessPlugin,Audit Classified Access Plugin configurations>> for all possible configurations.

