package org.codice.alliance.video.stream.mpegts.netty;

import org.jcodec.containers.mps.MTSUtils;

/**
 * Created by glenhein on 6/28/16.
 */
public enum StreamType {

    RESERVED,VIDEO_MPEG1,VIDEO_MPEG2,AUDIO_MPEG1,AUDIO_MPEG2,PRIVATE_SECTION,
    PRIVATE_DATA,MHEG,DSM_CC,ATM_SYNC,DSM_CC_A,DSM_CC_B,DSM_CC_C,DSM_CC_D,MPEG_AUX,AUDIO_AAC_ADTS,
    VIDEO_MPEG4,AUDIO_AAC_LATM,FLEXMUX_PES,FLEXMUX_SEC,DSM_CC_SDP,META_PES,META_SEC,
    DSM_CC_DATA_CAROUSEL,DSM_CC_OBJ_CAROUSEL,DSM_CC_SDP1,IPMP,VIDEO_H264,AUDIO_AAC_RAW,SUBS,
    AUX_3D,VIDEO_AVC_SVC,VIDEO_AVC_MVC,VIDEO_J2K,VIDEO_MPEG2_3D,VIDEO_H264_3D,VIDEO_CAVS,IPMP_STREAM,
    AUDIO_AC3,AUDIO_DTS;

    public static StreamType lookup(int tag) {
        return RESERVED;
    }

}
